# Compute proportion of samples containing analysis taxa

Names <- c( "Brachycyrtinae",
            "Pachyneuridae",
            "Gasteruptiidae.Aulacidae",
            "Neorhacodini",
            "Diacritinae",
            "Rhyssinae",
            "Strepsiptera",
            "Conopidae",
            "Odonata",
            "Small.parasitic.aculeate.families",
            "Dixidaee",
            "Eumeninaee",
            "Evaniidae",
            "Therevidae",
            "Aulacigastridae",
            "Phrudus.group",
            "Xoridinae",
            "Asilidae",
            "Heloridae",
            "Piophilidae",
            "Mymar",
            "Omphale",
            "Poemeniinae",
            "Milichiidae.excl.Phyllomyza",
            "Eupelmidae",
            "Trixoscelididae",
            "Acartophthalmidae",
            "Anthomyzidae",
            "Banchini",
            "Asteiidae",
            "Tephritidae.Ulidiidae",
            "Bethylidae",
            "Chrysididae",
            "Clusiidae",
            "Dryomyzidae",
            "Netelia",
            "Anomaloninae",
            "Ismaridae",
            "Pallopteridae",
            "Plecoptera",
            "Adelognathinae",
            "Lonchaeidae",
            "Sepsidae",
            "Pompilidae",
            "Dermaptera",
            "Small.mycetophiloid.families",
            "Porricondylinae.s.lat",
            "Syrphidae",
            "Adeliini",
            "Sciomyzidae",
            "Sphecidae",
            "Diplazontinae",
            "Dryinidae.Embolemidae",
            "Lauxaniidae",
            "Vespinae",
            "Meteorini",
            "Auchenorrhyncha.excl.Delphacidae",
            "Thysanoptera",
            "Figitidae.excl.Charipinae",
            "Symphyta",
            "Trichoptera",
            "Macrolepidoptera",
            "Rogadinae",
            "Ichneumoninae.excl.Phaeogenini",
            "Chloropidae",
            "Cheloninae.excl.Adeliini",
            "Heleomyzidae.Odiniidae",
            "Psocoptera",
            "Formicidae",
            "Pimplinae",
            "Dolichopodidae",
            "Drosophilidae",
            "Muscidae",
            "Microlepidoptera",
            "Platygastridae",
            "Psylloidea",
            "Coleoptera",
            "Mycetophilidae.Keroplatidae",
            "Phoridae"
            )

G <- list(  Brachycyrtinae="Brachycyrtinae",
            Pachyneuridae = "Pachyneuridae",
            Gasteruptiidae.Aulacidae = c("Gasteruptiidae  ","Aulacidae"),
            Neorhacodini = "Neorhacodinae",
            Diacritinae = "Diacritinae",
            Rhyssinae = "Rhyssinae",
            Strepsiptera = "Strepsiptera",
            Conopidae = "Conopidae",
            Odonata = "Odonata",
            Small.parasitic.aculeate.families = c("Mutillidae","Myrmosidae","Tiphiidae","Methochidae","Sapygidae"),
            Dixidae = "Dixidae",
            Eumeninae = "Vespidae",
            Evaniidae = "Evaniidae",
            Therevidae = "Therevidae",
            Aulacigastridae = "Aulacigasteridae",
            Phrudus.group = "Phrudinae",
            Xoridinae = "Xoridinae",
            Asilidae = "Asilidae",
            Heloridae = "Heloridae",
            Piophilidae = "Piophilidae",
            Mymar = c("Mymar","Mymar pulchellum","Mymar regale","Mymar taprobanicum"),
            Omphale = "Eulophidae",
            Poemeniinae = "Poemeniinae",
            Milichiidae.excl.Phyllomyza = "Milichiidae",
            Eupelmidae = c("Eupelmidae","Eupelmes vesicularis"),
            Trixoscelididae = "Trixoscelididae",
            Acartophthalmidae = "Acartophthalmidae",
            Anthomyzidae = "Anthomyzidae",
            Banchini = "Banchini",
            Asteiidae = "Asteiidae",
            Tephritidae.Ulidiidae = c("Tephritidae", "Ulididae"),
            Bethylidae = "Bethylidae",
            Chrysididae = "Chrysididae",
            Clusiidae = "Clusiidae",
            Dryomyzidae = "Dryomyzidae",
            Netelia = "Netelia",
            Anomaloninae = "Anomaloninae",
            Ismaridae = c("Ismaridae","Ismarus","Ismarus halidayi"),
            Pallopteridae = "Pallopteridae",
            Plecoptera = "Plecoptera",
            Adelognathinae = "Adelognathinae",
            Lonchaeidae = "Lonchaeidae",
            Sepsidae = "Sepsidae",
            Pompilidae = "Pompilidae",
            Dermaptera = "Dermaptera",
            Small.mycetophiloid.families = c("Diadocidiidae", "Diadocidia", "Diadocidia ferruginosa", "Diadocidia spinosula", "Mycetobiidae", "Ditomyiidae"),
            Porricondylinae.s.lat = "Cecidomyiidae",
            Syrphidae = "Syrphidae",
            Adeliini = "Adeliinae",
            Sciomyzidae = "Sciomyzidae",
            Sphecidae = "Sphecidae sensu lato",
            Diplazontinae = "Diplazontinae",
            Dryinidae.Embolemidae = c("Dryinidae", "Embolemidae"),
            Lauxaniidae = "Lauxaniidae",
            Vespinae = c("Vespidae", "Vespa crabro"),
            Meteorini = c("Meteorinae", "Meteorini"),
            Auchenorrhyncha.excl.Delphacidae = "Auchenorrhyncha",
            Thysanoptera = "Thysanoptera",
            Figitidae.excl.Charipinae = "Figitidae",
            Symphyta = c("Symphyta","Tenthredinidae"),
            Trichoptera = "Trichoptera",
            Macrolepidoptera = "Lepidoptera",
            Rogadinae = "Rogadinae",
            Ichneumoninae.excl.Phaeogenini = c("Ichneumoninae","Ichneumonini"),
            Chloropidae = "Chloropidae",
            Cheloninae.excl.Adeliini = "Cheloninae",
            Heleomyzidae.Odiniidae = c("Heleomyzidae", "Odiniidae"),
            Psocoptera = "Psocoptera",
            Formicidae = "Formicidae",
            Pimplinae = c("Pimplinae","Ephialtini","Delomeristini","Pimplini","Polysphinctini"),
            Dolichopodidae = "Dolichopodidae",
            Drosophilidae = "Drosophilidae",
            Muscidae = "Muscidae",
            Microlepidoptera = "Lepidoptera",
            Platygastridae = c("Platygastridae","Platygastrinae","Inostemma"),
            Psylloidea = "Homoptera",
            Coleoptera = "Coleoptera",
            Mycetophilidae.Keroplatidae = c("Mycetophilidae", "Keroplatidae"),
            Phoridae = "Phoridae"
         )

Total <- c( "Ichneumonidae",
            "Nematocera",
            "Hymenoptera",
            "Ichneumonidae",
            "Ichneumonidae",
            "Ichneumonidae",
            "Arthropoda",
            "Brachycera",
            "Arthropoda",
            "Hymenoptera",
            "Nematocera",
            "Hymenoptera",
            "Hymenoptera",
            "Brachycera",
            "Brachycera",
            "Ichneumonidae",
            "Ichneumonidae",
            "Brachycera",
            "Hymenoptera",
            "Brachycera",
            "Chalcidoidea",
            "Chalcidoidea",
            "Ichneumonidae",
            "Nematocera",
            "Chalcidoidea",
            "Brachycera",
            "Brachycera",
            "Brachycera",
            "Ichneumonidae",
            "Brachycera",
            "Brachycera",
            "Hymenoptera",
            "Hymenoptera",
            "Brachycera",
            "Brachycera",
            "Ichneumonidae",
            "Ichneumonidae",
            "Hymenoptera",
            "Brachycera",
            "Arthropoda",
            "Ichneumonidae",
            "Brachycera",
            "Brachycera",
            "Hymenoptera",
            "Arthropoda",
            "Nematocera",
            "Nematocera",
            "Brachycera",
            "Braconidae",
            "Brachycera",
            "Hymenoptera",
            "Ichneumonidae",
            "Hymenoptera",
            "Brachycera",
            "Hymenoptera",
            "Braconidae",
            "Arthropoda",
            "Arthropoda",
            "Hymenoptera",
            "Hymenoptera",
            "Arthropoda",
            "Arthropoda",
            "Braconidae",
            "Ichneumonidae",
            "Brachycera",
            "Braconidae",
            "Brachycera",
            "Arthropoda",
            "Hymenoptera",
            "Ichneumonidae",
            "Brachycera",
            "Brachycera",
            "Brachycera",
            "Arthropoda",
            "Hymenoptera",
            "Arthropoda",
            "Arthropoda",
            "Nematocera",
            "Brachycera"
            )
 
Tiers <- list ( Arthropoda = c(
                "Acari",
                "Annelida",
                "Araneae",
                "Auchenorrhyncha",
                "Blattodea",
                "Brachycera",
                "Coleoptera",
				"Collembola",
				"Dermaptera",
				"Ephemeroptera",
				"Heteroptera",
				"Hymenoptera",
				"Isopoda",
				"Lepidoptera",
				"Mecoptera",
				"Megaloptera",
				"Mollusca",
				"Myriapoda",
				"Nematocera",
				"Neuroptera",
				"Odonata",
				"Opiliones",
				"Orthoptera",
				"Phoridae",
				"Phthiraptera",
				"Plecoptera",
				"Pseudoscorpionida",
				"Psocoptera",
				"Raphidioptera",
				"Siphonaptera",
				"Sternorrhyncha",
				"Strepsiptera",
				"Thysanoptera",
				"Trichoptera"
               ),

            Hymenoptera = c(
				"Apoidea",
				"Aulacidae",
				"Bethylidae ",
				"Braconidae",
				"Ceraphronidae ",
				"Chalcidoidea",
				"Chrysididae",
				"Cynipidae",
				"Scelionidae",
				"Diapriidae",
				"Diapriidae",
				"Dryinidae",
				"Embolemidae",
				"Eumeninae",
				"Evaniidae",
				"Figitidae",
				"Charipinae",
				"Formicidae",
				"Gasteruptiidae",
				"Heloridae",
				"Ichneumonidae",
				"Ismaridae",
				"Megaspilidae",
				"Mutillidae",
				"Mymaridae",
				"Platygastridae",
				"Pompilidae",
				"Proctotrupidae",
				"Sphecidae",
				"Tenthredinidae",
				"Symphyta",
				"Tiphiidae",
				"Vanhorniidae",
				"Vespidae"
                ),

            Ichneumonidae = c(
				"Acaenitinae",
				"Adelognathinae",
				"Agriotypinae",
				"Alomyinae",
				"Anomaloninae",
				"Atrophini",
				"Banchinae",
				"Banchini",
				"Brachycyrtinae",
				"Campopleginae",
				"Collyriinae",
				"Cremastinae",
				"Cryptinae",
				"Cryptini",
				"Ctenopelmatinae",
				"Ctenopelmatini",
				"Cylloceriinae",
				"Diacritinae",
				"Diplazontinae",
				"Ephialtini",
				"Eucerotinae",
				"Euryproctini",
				"Exenterini",
				"Glyptini",
				"Helictes group",
				"Hemigastrini",
				"Hybrizontinae",
				"Ichneumoninae",
				"Ichneumonini",
				"Idiogrammatini",
				"Lycorininae",
				"Mesochorinae",
				"Mesoleiini",
				"Metopiinae",
				"Microleptinae",
				"Neorhacodini",
				"Oedemopsini",
				"Olethrodotini",
				"Ophioninae",
				"Orthocentrinae",
				"Orthocentrus group",
				"Orthopelmatinae",
				"Oxytorinae",
				"Perilissini",
				"Phaeogenini",
				"Phrudini",
				"Phygadeuontini",
				"Phytodietini",
				"Pimplinae",
				"Pimplini",
				"Pionini",
				"Poemeniinae",
				"Polysphincta group",
				"Rhyssinae",
				"Scolobatini",
				"Sphinctini",
				"Stilbopinae",
				"Tersilochinae",
				"Tryphoninae",
				"Tryphonini",
				"Xoridinae"
                ),

            Braconidae = c(
				"Adeliinae",
				"Agathidinae",
				"Alysiinae",
				"Aphidiinae",
				"Blacinae",
				"Braconinae",
				"Cardiochilinae",
				"Cenocoeliinae",
				"Charmontinae",
				"Cheloninae",
				"Doryctinae",
				"Euphorinae",
				"Exothecinae",
				"Gnamptodontinae",
				"Helconinae",
				"Histeromerinae",
				"Homolobinae",
				"Horminae",
				"Ichneutinae",
				"Lysiterminae",
				"Macrocentrinae",
				"Meteorinae",
				"Microgastrinae",
				"Microtypinae",
				"Miracinae",
				"Neoneurinae",
				"Opiinae",
				"Orgilinae ",
				"Pambolinae ",
				"Proteropinae ",
				"Rhyssalinae ",
				"Rogadinae ",
				"Sigalphinae "
                ),

            Chalcidoidea = c(
				"Aphelinidae",
				"Chalcididae",
				"Encyrtidae",
				"Eulophidae",
				"Eupelmidae",
				"Eurytomidae",
				"Mymar pulchellum",
				"Mymar regale",
				"Mymar sp.",
				"Mymaridae",
				"Mymarommatidae",
				"Ormyridae ",
				"Perilampidae",
				"Pteromalidae",
				"Signiphoridae",
				"Tetracampidae",
				"Torymidae",
				"Trichogrammatidae"
                ),

            Brachycera = c(
				"Acarthophthalmidae ",
				"Acroceridae",
				"Agromyzidae",
				"Anthomyiidae",
				"Anthomyzidae",
				"Asilidae",
				"Asteiidae",
				"Athericidae",
				"Aulacigasteridae",
				"Bombyliidae",
				"Brachystomatidae",
				"Braulidae",
				"Calliphoridae",
				"Camillidae",
				"Campichoetidae",
				"Carnidae",
				"Chamaemyiidae",
				"Chiropteromyzidae",
				"Chloropidae",
				"Chyromyidae",
				"Clusiidae",
				"Coelopidae",
				"Coenomyiidae",
				"Conopidae",
				"Diastatidae",
				"Dolichopodidae",
				"Drosophilidae",
				"Dryomyzidae",
				"Empidoidea",
				"Ephydridae",
				"Fanniidae",
				"Gasterophilidae",
				"Helcomyzidae",
				"Heleomyzidae",
				"Heterocheilidae",
				"Hippoboscidae",
				"Hypodermatidae",
				"Lauxaniidae",
				"Lonchaeidae",
				"Lonchopteridae",
				"Megamerinidae",
				"Micropezidae",
				"Milichiidae",
				"Muscidae",
				"Nycteribiidae",
				"Odiniidae",
				"Oestridae",
				"Opetiidae",
				"Opomyzidae",
				"Pallopteridae",
				"Periscelididae",
				"Phaeomyiidae",
				"Phoridae",
				"Piophilidae",
				"Pipunculidae",
				"Platypezidae",
				"Platystomatidae",
				"Pseudopomyzidae",
				"Psilidae",
				"Rhagionidae",
				"Rhinophoridae",
				"Sarcophagidae",
				"Scathophagidae",
				"Scenopinidae",
				"Sciomyzidae",
				"Sepsidae",
				"Sphaeroceridae",
				"Stenomicridae",
				"Stratiomyidae",
				"Strongylophthalmyiidae",
				"Syrphidae",
				"Tabanidae",
				"Tachinidae",
				"Tanypezidae",
				"Tephritidae",
				"Tethinidae",
				"Therevidae",
				"Trixoscelididae",
				"Ulidiidae",
				"Xylomyidae",
				"Xylophagidae"
                ),

            Nematocera = c(
				"Anisopodidae",
				"Bibionidae",
				"Bolitophilidae",
				"Canthyloscelidae",
				"Cecidomyiidae",
				"Ceratopogonidae",
				"Chaoboridae",
				"Chironomidae",
				"Culicidae",
				"Cylindrotomidae",
				"Diadocidiidae",
				"Ditomyiidae",
				"Dixidae",
				"Keroplatidae",
				"Limoniidae",
				"Mycetobiidae",
				"Mycetophilidae",
				"Pachyneuridae",
				"Pediciidae",
				"Psychodidae",
				"Ptychopteridae",
				"Scatopsidae",
				"Sciaridae",
				"Simuliidae",
				"Synnereuridae",
				"Thaumaleidae",
				"Tipulidae",
				"Trichoceridae"
                )
            )

D <- read.csv( "total_smtp_sorting_data_2017-09-21.csv" )

x <- numeric( length( G ) )
y <- numeric( length( G ) )

for ( i in 1:length( G ) )
{
    groups <- G[[i]]

    E <- D[ D$Taxon %in% groups, ]

    x[i] <- length( unique( E$Event.ID ) )

    E <- D[ D$Taxon %in% Tiers[[ Total[i] ]], ]

    y[i] <- length( unique( E$Event.ID ) )

}

Z <- data.frame( x, y )
colnames(Z) <- c( "Samples", "Total" )
Z$Taxon <- Names
Z$HigherTaxon <- Total
Z <- Z[ , c(3, 4, 1, 2) ]
Z$EstimatedProp <- Z$Samples / Z$Total

